return {
	['muteWega'] = false,
	['detailedDescs'] = false,
	["resetAchievements"] = nil,
	["chadNova"] = nil,
	['enableVinkers'] = true,
	['enableJoelkers'] = true,
	['enableOtherJokers'] = true,
	['enableConsumables'] = true,
	['enableChallenges'] = true,
	['enableAchievements'] = true,
	['enableBoosters'] = true,
	['enableTags'] = true,
	['enableVouchers'] = true,
	['enableEditions'] = true,
	['enableDecks'] = true,
	['enableBlinds'] = true,
	['enableSkins'] = true,
	['enableMusic'] = true,
	['enableLogo'] = true,
	['enableColors'] = true,
	['enableTarotSkins'] = true,
	['enableEasterEggs'] = true,
}